{% set version = "1.6" %}

package:
  name: pythonicdisort
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pythonicdisort/pythonicdisort-{{ version }}.tar.gz
  sha256: bfa6e1caea7d807c7ef4b5f1551e474d81bfd0c4ba1e7d772c8f408a9b97f114

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
    - wheel
  run:
    - python >={{ python_min }}
    - numpy >=1.8.0
    - scipy >=1.8.0

test:
  imports:
    - PythonicDISORT
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/LDEO-CREW/Pythonic-DISORT
  summary: Discrete Ordinates Solver for the (1D) Radiative Transfer Equation in a single or multi-layer atmosphere.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dhjx1996
    - RobertPincus
